### ISSUE TITLE
EEE: Design Review

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/eating-exercise-and-energy#10]
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
