### ISSUE TITLE
EEE: QA RC test

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/eating-exercise-and-energy#12]
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)
