### ISSUE TITLE
EEE: Publication

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/eating-exercise-and-energy#13]
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [ ] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
  - [ ] Add CT tests for public query parameters
  - [ ] Auxiliary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Accessibility features
  - [ ] Email announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)

- [ ] **Post-publication items** 
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Review legacy gold star activities, copy over if appropriate
  - [ ] Email announcement language
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Hold postmortem if applicable (Date: //) 
- [ ] **Published** (Date: //) 
  - [ ] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
