### ISSUE TITLE
EEE: Development

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/eating-exercise-and-energy#8]
- [ ] **Repository created** (Date: //)
  - [ ] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (Developer team, QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to perennial/data/active-repos
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //)
