### ISSUE TITLE
EEE: QA dev test

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/eating-exercise-and-energy#9]
- [ ] **Legacy sim tested for bugs**; issues reported in repo
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing complete** (Date: //)
